import { MD3LightTheme } from 'react-native-paper';

export const colors = {
  primary: '#D35400',
  primaryDark: '#963B00',
  primarySoft: '#FFF0E5',
  secondary: '#F2A65A',
  secondarySoft: '#FFF6E8',
  accent: '#23766D',
  accentSoft: '#E8F4F2',
  blue: '#3F6F8F',
  blueSoft: '#EAF2F7',
  navy: '#18354E',
  navySoft: '#EAF0F5',
  sage: '#5E7967',
  sageSoft: '#EDF4EF',
  violet: '#6B5C8D',
  violetSoft: '#F0EDF7',
  gold: '#B9791D',
  goldSoft: '#FFF5DF',
  background: '#F7F4F0',
  surface: '#FCFBF9',
  surfaceRaised: '#FFFFFF',
  surfaceSoft: '#F7F2EC',
  surfaceStrong: '#EEE7DF',
  charcoal: '#232930',
  charcoalSoft: '#3D444C',
  border: '#E3DBD2',
  text: '#23272B',
  muted: '#686F72',
  success: '#2E7D32',
  danger: '#B42318',
  warning: '#B76610',
  info: '#356C95',
} as const;

export const paperTheme = {
  ...MD3LightTheme,
  roundness: 12,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary,
    onPrimary: '#FFFFFF',
    primaryContainer: colors.primarySoft,
    onPrimaryContainer: colors.primaryDark,
    secondary: colors.secondary,
    secondaryContainer: colors.secondarySoft,
    onSecondaryContainer: colors.charcoal,
    tertiary: colors.accent,
    tertiaryContainer: colors.accentSoft,
    background: colors.background,
    surface: colors.surfaceRaised,
    surfaceVariant: colors.surfaceSoft,
    outline: colors.border,
    outlineVariant: '#ECE5DE',
    onSurface: colors.text,
    onSurfaceVariant: colors.muted,
    error: colors.danger,
  },
};
