import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  timeout: 150_000,
  expect: { timeout: 20_000 },
  fullyParallel: false,
  workers: process.env.CI ? 1 : undefined,
  retries: 1,
  reporter: [['list'], ['html', { open: 'never', outputFolder: 'playwright-report' }]],
  use: {
    baseURL: process.env.E2E_BASE_URL || 'https://www.buildpair.co.uk',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    actionTimeout: 20_000,
    navigationTimeout: 30_000,
  },
  projects: [
    {
      name: 'setup',
      testMatch: /global\.setup\.mjs/,
      teardown: 'cleanup',
    },
    {
      name: 'cleanup',
      testMatch: /global\.teardown\.mjs/,
    },
    {
      name: 'real-signup-journey',
      testMatch: /real-signup-journey\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'desktop-auth-entrypoints',
      testMatch: /auth-entrypoints\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'desktop-auth-recovery',
      testMatch: /auth-recovery\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'desktop-account-deletion',
      testMatch: /account-deletion\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'desktop-onboarding-validation',
      testMatch: /onboarding-validation\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'desktop-core-flow',
      testMatch: /core-flow\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'desktop-marketplace-features',
      testMatch: /marketplace-features\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'desktop-abuse-security',
      testMatch: /abuse-security\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'desktop-job-draft-recovery',
      testMatch: /job-draft-recovery\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'desktop-dual-mode',
      testMatch: /dual-mode\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'desktop-route-coverage',
      testMatch: /route-coverage\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'desktop-public-marketplace',
      testMatch: /public-marketplace\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'small-android-route-coverage',
      testMatch: /route-coverage\.spec\.mjs/,
      use: { ...devices['Pixel 5'] },
      dependencies: ['setup'],
    },
    {
      name: 'small-android-public-marketplace',
      testMatch: /public-marketplace\.spec\.mjs/,
      use: { ...devices['Pixel 5'] },
      dependencies: ['setup'],
    },
    {
      name: 'external-integrations',
      testMatch: /external-integrations\.spec\.mjs/,
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup'],
    },
    {
      name: 'small-android-public-ui',
      testMatch: /mobile-layout\.spec\.mjs/,
      use: { ...devices['Pixel 5'] },
      dependencies: ['setup'],
    },
  ],
});
