import { Text } from 'react-native';
import { colors } from '@/constants/theme';

type Props = {
  name: string;
  color?: string;
  size: number;
  direction?: 'ltr' | 'rtl';
};

const glyphs: Record<string, string> = {
  'home-outline': '⌂',
  home: '⌂',
  'home-city-outline': '▦',
  'home-roof': '⌂',
  'briefcase-search-outline': '⌕',
  'briefcase-outline': '▣',
  'briefcase-plus-outline': '+',
  'message-text-outline': '●',
  'message-outline': '●',
  'message-alert-outline': '!',
  'account-circle-outline': '○',
  'account-outline': '○',
  'account-plus': '+',
  'account-group-outline': '◎',
  'account-hard-hat-outline': '◉',
  'account-arrow-right': '›',
  'account-arrow-left': '‹',
  'account-edit-outline': '✎',
  magnify: '⌕',
  'clipboard-text-outline': '▤',
  'file-document-edit-outline': '▤',
  'file-edit-outline': '✎',
  'book-open-page-variant-outline': '▤',
  'check-circle-outline': '✓',
  'check-circle': '✓',
  check: '✓',
  'check-decagram-outline': '✓',
  'shield-check-outline': '✓',
  'shield-check': '✓',
  'shield-alert-outline': '!',
  star: '★',
  'star-outline': '☆',
  'heart-outline': '♡',
  heart: '♥',
  'image-multiple-outline': '▧',
  'image-outline': '▧',
  'image-plus': '+',
  'camera-outline': '◉',
  'gift-outline': '✦',
  plus: '+',
  'plus-circle-outline': '+',
  close: '×',
  'close-circle-outline': '×',
  logout: '↪',
  'open-in-new': '↗',
  phone: '☎',
  'email-outline': '@',
  bank: '£',
  cash: '£',
  'currency-gbp': '£',
  'credit-card': '£',
  'credit-card-outline': '£',
  'map-marker-outline': '⌖',
  'map-marker-radius': '⌖',
  'map-marker': '⌖',
  'clock-outline': '◷',
  'calendar-clock': '◷',
  'timeline-clock-outline': '◷',
  'calendar-outline': '□',
  calendar: '□',
  'calendar-check': '✓',
  'calendar-check-outline': '✓',
  creation: '✦',
  'hammer-wrench': '✦',
  tools: '✦',
  'water-pump': '≈',
  'lightning-bolt-outline': 'ϟ',
  'format-paint': '▰',
  'countertop-outline': '▤',
  shower: '≈',
  'chart-line': '↗',
  'chart-box-outline': '▦',
  'bell-outline': '♢',
  'bell-plus-outline': '+',
  'eye-outline': '○',
  'information-outline': 'i',
  'alert-circle-outline': '!',
  'alert-outline': '!',
  alert: '!',
  'pause-circle-outline': 'Ⅱ',
  'lock-outline': '▣',
  'lock-open-outline': '◇',
  'flask-outline': '◇',
  'share-variant': '↗',
  'chevron-up': '⌃',
  'chevron-down': '⌄',
  'chevron-right': '›',
  'chevron-left': '‹',
  'arrow-right': '→',
  'arrow-left': '←',
  send: '↑',
  'delete-outline': '×',
  'trash-can-outline': '×',
  'pencil-outline': '✎',
  pencil: '✎',
  refresh: '↻',
  'filter-variant': '≡',
  'dots-horizontal': '•••',
  menu: '≡',
  cancel: '×',
  'google-play': '▶',
  apple: '◆',
  settings: '⚙',
  'settings-outline': '⚙',
};

export function PaperIcon({ name, color = colors.muted, size }: Props) {
  const glyph = glyphs[name] ?? '□';
  return (
    <Text
      accessibilityElementsHidden
      importantForAccessibility="no"
      style={{
        color,
        fontSize: Math.max(12, size * 0.82),
        lineHeight: size,
        width: size,
        height: size,
        textAlign: 'center',
        fontWeight: '800',
      }}
    >
      {glyph}
    </Text>
  );
}
