import Head from 'expo-router/head';
import { type Href, Link } from 'expo-router';
import { Linking, ScrollView, StyleSheet, View } from 'react-native';
import { Text } from 'react-native-paper';
import { Button } from '@/components/BrandButton';
import { PublicFooter } from '@/components/PublicFooter';
import { PUBLIC_SHARE_IMAGE, PublicSeo } from '@/components/PublicSeo';
import { SemanticHeading } from '@/components/SemanticHeading';
import { colors, radii } from '@/constants/theme';

import { SEO_ADVICE_BATCH } from '@/lib/seo-advice-batch';

export function SeoAdviceBatchPage({slug}:{slug:string}) {
 const guide=SEO_ADVICE_BATCH.find(g=>g.slug===slug); if(!guide) return null;
 const canonical='https://www.buildpair.co.uk/advice/'+guide.slug;
 const schema={'@context':'https://schema.org','@type':'Article',headline:guide.title,description:guide.summary,datePublished:'2026-10-04',dateModified:'2026-10-04',mainEntityOfPage:canonical,image:PUBLIC_SHARE_IMAGE,author:{'@type':'Organization',name:'BuildPair',url:'https://www.buildpair.co.uk/'},publisher:{'@type':'Organization',name:'BuildPair',url:'https://www.buildpair.co.uk/'},inLanguage:'en-GB'};
 return <ScrollView style={styles.page} contentContainerStyle={styles.scroll}><PublicSeo title={guide.title} description={guide.summary}/><Head><link rel="canonical" href={canonical}/><script type="application/ld+json">{JSON.stringify(schema)}</script></Head><View style={styles.hero}><View style={styles.heroInner}><Text style={styles.eyebrow}>Homeowner · {guide.category}</Text><SemanticHeading level={1} style={styles.heroTitle}>{guide.title}</SemanticHeading><Text style={styles.heroBody}>{guide.summary}</Text><Text style={styles.meta}>Applies to: {guide.appliesTo} · Last checked: 4 October 2026</Text></View></View><View style={styles.shell}><View style={styles.notice}><Text style={styles.noticeTitle}>Key points</Text>{guide.keyPoints.map(p=><Text key={p} style={styles.bullet}>• {p}</Text>)}</View>{guide.sections.map(s=><View key={s.heading} style={styles.section}><SemanticHeading level={2} style={styles.sectionTitle}>{s.heading}</SemanticHeading>{(s.paragraphs??[]).map(p=><Text key={p} style={styles.body}>{p}</Text>)}{(s.bullets??[]).map(p=><Text key={p} style={styles.bullet}>• {p}</Text>)}</View>)}<View style={styles.sourceBox}><SemanticHeading level={2} style={styles.sectionTitle}>Sources and methodology</SemanticHeading><Text style={styles.body}>Pricing figures are third-party UK market budgeting references, not BuildPair prices or guaranteed local quotes. Legal and safety points are linked to current official guidance. Check the current source and your project circumstances before acting.</Text>{guide.sources.map(s=><Button key={s.url} mode="outlined" icon="open-in-new" onPress={()=>Linking.openURL(s.url)}>{s.publisher}: {s.title}</Button>)}</View><View style={styles.section}><SemanticHeading level={2} style={styles.sectionTitle}>Related BuildPair guides</SemanticHeading><View style={styles.related}>{guide.related.map(r=>{const x=SEO_ADVICE_BATCH.find(g=>g.slug===r);return x?<Link key={r} href={('/(public)/advice/'+r) as Href} asChild><Button mode="outlined">{x.title}</Button></Link>:null})}</View></View><View style={styles.disclaimer}><Text style={styles.meta}>BuildPair provides general information and signposting, not legal, structural, gas, electrical or building-control approval. Requirements and prices vary by location, property and scope.</Text></View><View style={styles.related}><Link href="/(public)/advice" asChild><Button mode="outlined">Back to Advice Hub</Button></Link><Link href="/(public)/directory" asChild><Button mode="contained">Find a trade</Button></Link></View></View><PublicFooter/></ScrollView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},scroll:{flexGrow:1},hero:{paddingHorizontal:16,paddingVertical:48,backgroundColor:colors.background},heroInner:{width:'100%',maxWidth:900,alignSelf:'center',gap:14},eyebrow:{color:colors.primary,fontWeight:'900',textTransform:'uppercase',letterSpacing:1.1},heroTitle:{color:colors.charcoal,fontSize:42,lineHeight:49,fontWeight:'900',letterSpacing:-1.1},heroBody:{color:colors.charcoalSoft,fontSize:18,lineHeight:28,maxWidth:780},meta:{color:colors.muted,fontSize:13,lineHeight:20},shell:{width:'100%',maxWidth:900,alignSelf:'center',paddingHorizontal:16,paddingBottom:48,gap:24},notice:{backgroundColor:colors.primarySoft,borderRadius:radii.xl,borderWidth:1,borderColor:'#F0C9AE',padding:22,gap:8},noticeTitle:{color:colors.charcoal,fontSize:20,fontWeight:'900'},section:{gap:10},sectionTitle:{color:colors.charcoal,fontSize:26,lineHeight:32,fontWeight:'900'},body:{color:colors.charcoalSoft,fontSize:16,lineHeight:25},bullet:{color:colors.charcoalSoft,fontSize:16,lineHeight:24},sourceBox:{backgroundColor:colors.surfaceRaised,borderRadius:radii.xl,borderWidth:1,borderColor:colors.border,padding:22,gap:12,alignItems:'flex-start'},related:{flexDirection:'row',flexWrap:'wrap',gap:10},disclaimer:{borderTopWidth:1,borderTopColor:colors.border,paddingTop:16}});