import { Link } from 'expo-router';
import { Text, View } from 'react-native';
import { Button } from 'react-native-paper';
import { PublicInfoPage, infoStyles } from '@/components/PublicInfoPage';
import { waitlistHref } from '@/lib/launch';

export default function ForTradespeoplePage() {
  return <PublicInfoPage
    eyebrow="For tradespeople"
    title="Win suitable work, present your business professionally and keep the job organised."
    intro="BuildPair gives tradespeople a professional profile, local marketplace opportunities, structured quoting and practical tools for managing work after the lead is won."
    sections={[
      { title: 'Surrey Founding 50', body: <View style={infoStyles.list}><Text style={infoStyles.item}>We’re onboarding the first 50 Surrey trades before public launch. Create your real BuildPair account and complete your business profile now. Jobs, quoting, messaging and BuildPay remain locked until launch, and your 3 months of Pro only starts when the marketplace opens.</Text><Link href={waitlistHref('trader', 'for-tradespeople-founding-50')} asChild><Button mode="contained">Create my launch-ready profile</Button></Link></View> },
      { title: 'Build a profile that shows what you actually do', body: 'Present your trade categories, services, experience, service area, work galleries, before-and-after projects, qualifications, registers and business links in one profile. The aim is to make relevant experience and workmanship easier for homeowners to assess.' },
      { title: 'Bring your reputation with you', body: 'Connect an approved Google business listing and BuildPair can show its Google rating and available Google reviews separately from reviews earned through BuildPair. BuildPair checks the listing against your saved business details before it can appear publicly; uncertain matches are held for admin review.' },
      { title: 'Choose the work you want to be found for', body: 'BuildPair separates broad trade categories from the services underneath them. Plan limits apply to main categories, while the services within those categories can be kept up to date as your business changes.' },
      { title: 'Find local opportunities in several ways', body: <View style={infoStyles.list}><Text style={infoStyles.item}>• Browse open marketplace jobs that match your category and service radius.</Text><Text style={infoStyles.item}>• Receive direct quote requests from homeowners who choose your searchable profile.</Text><Text style={infoStyles.item}>• Publish availability so customers can see when you may be able to take work.</Text><Text style={infoStyles.item}>• Use saved searches and alerts to surface relevant opportunities.</Text><Text style={infoStyles.item}>• Opt into emergency availability where it suits your business.</Text></View> },
      { title: 'Visit first when the job needs it', body: 'BuildPair does not expect you to price work blindly from a photograph. Where inspection is sensible, propose a site visit through the job. The homeowner confirms it and shares the private address. Once the confirmed visit has taken place, mark it complete and send the resulting structured quote through BuildPair.' },
      { title: 'Send clearer quotes', body: 'Structured quote fields keep scope, exclusions, start date, duration, deposit, payment stages, warranty and VAT information clear. AI quote assistance can help draft wording, while the tradesperson remains responsible for checking the final quote before it is sent.' },
      { title: 'BuildPay is optional, not compulsory', body: 'You can include BuildPay in a quote and choose whether to absorb its agreed cost or add the separately disclosed BuildPay service fee to the homeowner total. After an ordinary quote is accepted, either side can also propose paying outside BuildPair. The job only switches to direct payment when both sides explicitly agree.' },
      { title: 'Record changes before extra work starts', body: 'Variations can record the requested change, price effect, timing effect and approval status. That gives both sides a clearer record when the scope changes after the original quote.' },
      { title: 'Keep using BuildPair after the lead is won', body: 'Messaging, project stages, invoices, availability, project stories and analytics are designed to remain useful throughout the customer relationship, not just at the introduction.' },
      { title: 'Starter, Plus and Pro', body: <View style={infoStyles.list}><Text style={infoStyles.item}>• Starter: £0/month, up to 2 main categories, full profile setup and private preview. Starter profiles are not publicly visible.</Text><Text style={infoStyles.item}>• BuildPair Plus: £19.99/month, up to 4 main categories, public searchable profile, approved Google review connection, direct quote requests and 15 open-marketplace offers per month.</Text><Text style={infoStyles.item}>• BuildPair Pro: £29.99/month, up to 6 main categories, everything in Plus, 35 offers per month, advanced analytics, priority alerts and a modest search boost.</Text><Link href="/(public)/pricing" asChild><Button mode="outlined">Compare memberships</Button></Link></View> },
      { title: 'BuildPair Rewards', body: <View style={infoStyles.list}><Text style={infoStyles.item}>Launch members can qualify for free Plus or Pro periods, and genuine completed work, BuildPay completions and other eligible activity can unlock further rewards.</Text><Link href="/(public)/rewards" asChild><Button mode="outlined">See BuildPair Rewards</Button></Link></View> },
      { title: 'Professional responsibilities remain yours', body: 'Tradespeople remain responsible for accurate profile claims, safe working practices and any registration, qualification, licence, insurance, notification or permission required for the work they undertake. BuildPair can organise evidence and marketplace information but does not replace a regulator or competent-person scheme.' },
    ]}
  />;
}