import { Link } from 'expo-router';
import { Text, View } from 'react-native';
import { Button } from 'react-native-paper';
import { PublicInfoPage, infoStyles } from '@/components/PublicInfoPage';
import { waitlistHref } from '@/lib/launch';

export default function ForTradespeoplePage() {
  return <PublicInfoPage
    eyebrow="For tradespeople"
    title="Win suitable work, present your business professionally and keep the job organised."
    intro="BuildPair gives tradespeople a professional profile, local marketplace opportunities, structured quoting and practical tools for managing work after the lead is won."
    sections={[
      { title: 'Surrey Founding 50', body: <View style={infoStyles.list}><Text style={infoStyles.item}>We’re onboarding the first 50 Surrey trades before public launch. Create your real BuildPair account and complete your business profile now. Jobs, quoting, messaging and BuildPay remain locked until launch, and your 3 months of Pro only starts when the marketplace opens.</Text><Link href={waitlistHref('trader', 'for-tradespeople-founding-50')} asChild><Button mode="contained">Create my launch-ready profile</Button></Link></View> },
      { title: 'Build a profile that shows what you actually do', body: 'Present your trade categories, services, experience, service area, work galleries, before-and-after projects, qualifications, registers and business links in one profile. The aim is to make relevant experience and workmanship easier for homeowners to assess.' },
      { title: 'Bring your reputation with you', body: 'Connect an approved Google business listing and BuildPair can show its Google rating and available Google reviews separately from reviews earned through BuildPair. BuildPair checks the listing against your saved business details before it can appear publicly; uncertain matches are held for admin review.' },
      { title: 'Choose the work you want to be found for', body: 'BuildPair separates broad trade categories from the services underneath them. Plan limits apply to main categories, while the services within those categories can be kept up to date as your business changes.' },
      { title: 'Find local opportunities in several ways', body: <View style={infoStyles.list}><Text style={infoStyles.item}>• Browse open marketplace jobs that match your category and service radius.</Text><Text style={infoStyles.item}>• Receive direct quote requests from homeowners who choose your searchable profile.</Text><Text style={infoStyles.item}>• Publish availability so customers can see when you may be able to take work.</Text><Text style={infoStyles.item}>• Use saved searches and alerts to surface relevant opportunities.</Text><Text style={infoStyles.item}>• Opt into emergency availability where it suits your business.</Text></View> },
      { title: 'Visit first when the job needs it', body: 'BuildPair does not expect you to price work blindly from a photograph. Where inspection is sensible, propose a site visit through the job. The homeowner confirms it and shares the private address. Once the confirmed visit has taken place, mark it complete and send the resulting structured quote through BuildPair.' },
      { title: 'Use BuildPair for customers you found anywhere', body: 'Create an itemised quote for a referral, phone enquiry, social-media lead or existing customer without needing a BuildPair marketplace job. The customer gets a secure quote link, can accept online, and the accepted quote can later become a managed BuildPair project without retyping the scope, price or payment stages.' },
      { title: 'Send clearer quotes and keep revisions', body: 'The Quote Builder keeps scope, exclusions, itemised labour/materials/overheads, VAT, timing, warranty and payment stages clear. Sent outside-customer quotes can be revised without overwriting the earlier record. Once a quote is accepted, later commercial changes belong in the project variation record.' },
      { title: 'BuildPay is optional, not compulsory', body: 'Either side can ask to use BuildPay, but the party requesting it carries the cost. If you include BuildPay in your quote, its agreed cost is recovered from controlled service payouts rather than added to the homeowner. If the homeowner asks for BuildPay instead, their disclosed service fee is added to their BuildPay total. Either side can still propose paying outside BuildPair, and the job only switches to direct payment when both sides explicitly agree.' },
      { title: 'Record changes before extra work starts', body: 'Variations can record the requested change, price effect, timing effect and approval status. That gives both sides a clearer record when the scope changes after the original quote.' },
      { title: 'Keep using BuildPair after the lead is won', body: 'The managed project workspace can hold tasks, progress notes, material and expense records, snagging, handover and warranty notes alongside messages, payment stages, variations, invoices, completion and review. BuildPair is intended to stay useful after the introduction.' },
      { title: 'Project+ for customer planning', body: 'BuildPair Pro includes Project+ AI planning and room-concept tools. A Pro tradesperson can use the same tools with a customer to clarify a bathroom, kitchen or room brief before turning that discussion into a quote.' },
      { title: 'Starter, Core, Plus and Pro', body: <View style={infoStyles.list}><Text style={infoStyles.item}>• Starter: £0/month, up to 2 main categories, complete profile setup, gallery and marketplace browsing.</Text><Text style={infoStyles.item}>• BuildPair Core: £9.99/month, searchable profile, 5 marketplace opportunities, outside-customer quotes/invoices, messaging, 1 saved search, basic analytics and simple availability.</Text><Text style={infoStyles.item}>• BuildPair Plus: £19.99/month, up to 4 categories, 15 open-marketplace opportunities, unlimited direct requests, full Quote Builder, outside-customer managed projects, staged BuildPay, Google reviews, AI tools, 5 saved searches and up to 12 weeks of availability.</Text><Text style={infoStyles.item}>• BuildPair Pro: £29.99/month, up to 6 categories, 35 opportunities, advanced analytics, priority alerts, six-month availability, unlimited saved searches, reusable templates, advanced project tools and Project+ included.</Text><Link href="/(public)/pricing" asChild><Button mode="outlined">Compare memberships</Button></Link></View> },
      { title: 'BuildPair Rewards', body: <View style={infoStyles.list}><Text style={infoStyles.item}>Launch members can qualify for free Plus or Pro periods, and genuine completed work, BuildPay completions and other eligible activity can unlock further rewards.</Text><Link href="/(public)/rewards" asChild><Button mode="outlined">See BuildPair Rewards</Button></Link></View> },
      { title: 'Professional responsibilities remain yours', body: 'Tradespeople remain responsible for accurate profile claims, safe working practices and any registration, qualification, licence, insurance, notification or permission required for the work they undertake. BuildPair can organise evidence and marketplace information but does not replace a regulator or competent-person scheme.' },
    ]}
  />;
}