import { PublicInfoPage } from '@/components/PublicInfoPage';

export default function PaymentsPage() {
  return <PublicInfoPage
    eyebrow="Payments"
    title="How BuildPay and direct payments work"
    intro="After a BuildPair quote is accepted, the homeowner can use BuildPay for Stripe-processed staged payments or pay the tradesperson directly. The quote and project can stay in BuildPair either way, but the payment protections are deliberately different."
    updated="11 September 2026"
    sections={[
      { title: '1. Agree the quote before money moves', body: 'The tradesperson sends a structured BuildPair quote showing scope, exclusions, labour/service, materials, VAT where applicable, timing and a payment schedule. The homeowner can request different service-stage splits before accepting, but the quote total and quoted materials amount cannot be silently changed. Any homeowner-edited stage plan must be accepted by the tradesperson.' },
      { title: '2. Choose BuildPay or direct payment', body: 'After the quote is accepted, the homeowner chooses how the money will move. BuildPay means Stripe processes the supported payments and BuildPair operates the recorded stage-release workflow. Direct payment means the homeowner and tradesperson arrange payment between themselves, for example by bank transfer or another agreed method. BuildPair can keep the project record but does not process that money.' },
      { title: '3. BuildPay materials are paid first', body: 'Where the accepted quote includes materials, the payment schedule contains the exact quoted materials amount as the first materials stage. When Stripe confirms that payment, BuildPair instructs transfer of that materials amount to the tradesperson so procurement can begin. Materials are not subject to a later workmanship-release approval.' },
      { title: '4. Deposits, progress stages and final payments are controlled', body: 'A BuildPay deposit, progress stage or final stage is charged to the homeowner but is not transferred to the tradesperson merely because the card payment succeeded. The tradesperson must reach the recorded completion point and request release. The homeowner then reviews that stage and either approves release or raises an issue. Later stages remain locked until earlier stages are completed.' },
      { title: '5. One obvious next step', body: 'BuildPay progresses one agreed stage at a time. After a stage is released, the next agreed stage becomes the action to fund. This keeps materials, work progress and payment decisions attached to the same project instead of leaving either party to reconstruct the arrangement from bank transfers and chat messages.' },
      { title: '6. Issues before release', body: 'If the homeowner raises an issue before a controlled BuildPay stage is transferred, that release is paused. The tradesperson can respond in the project record. The homeowner can resolve the issue and return the stage to release review, request a refund of the unreleased stage, or escalate the record for BuildPair admin attention. BuildPair admin review helps manage the platform workflow and evidence record; it is not an inspection of workmanship or an automatic legal adjudication.' },
      { title: '7. Refunds and payment disputes', body: 'An unreleased BuildPay stage can be refunded where the workflow and payment position allow it, including where both parties agree a refund. Stripe, card-network, fraud, refund and chargeback procedures can also apply separately. Once money has already been transferred to a tradesperson, BuildPair cannot promise that the transfer can simply be reversed.' },
      { title: '8. BuildPair and Stripe fees', body: 'BuildPair currently charges the tradesperson 1% of the accepted labour/service amount only. Materials and VAT are excluded from the BuildPair 1% fee base. Stripe processing costs are recovered at the actual recorded cost from controlled service payouts as the job progresses. BuildPair does not add its 1% fee to the quoted materials amount.' },
      { title: '9. Direct payments remain allowed', body: 'A tradesperson does not have to force every customer through BuildPay simply because the introduction happened on BuildPair. If both sides choose direct payment, BuildPair may record that the homeowner says a payment was sent and the tradesperson says it was received. Those confirmations are user declarations only. BuildPair did not receive, hold, protect, release, refund or independently verify the money.' },
      { title: '10. What changes with direct payment', body: 'BuildPay stage protection, Stripe transaction records and BuildPair release controls do not apply to money paid directly. The tradesperson remains responsible for the work and both parties remain responsible for their own agreement and payment conduct. Choosing direct payment does not remove statutory consumer rights, contractual rights or any liability that cannot lawfully be excluded.' },
      { title: '11. BuildPair is not an escrow or workmanship guarantor', body: 'BuildPay is a payment workflow, not a legal escrow account. BuildPair does not attend the property, certify workmanship or decide whether building work complies with a contract, regulation or professional standard. The recorded quote, messages, variations, stage actions and payment events are intended to make the project clearer and easier to evidence.' },
    ]}
  />;
}
