import { PublicInfoPage } from '@/components/PublicInfoPage';

export default function PaymentsPage() {
  return <PublicInfoPage
    eyebrow="Payments"
    title="How BuildPair staged payments work"
    intro="BuildPair lets an accepted quote continue as a managed project with an agreed payment schedule. Homeowners fund the next agreed stage when it is needed rather than paying the whole project price upfront. You can also choose to pay privately, but the payment-stage controls described here then do not apply."
    updated="9 September 2026"
    sections={[
      { title: '1. The payment plan starts with the quote', body: 'The tradesperson proposes the total quote and a payment schedule. That schedule can include a materials payment, deposit, progress stages and a final payment. Each progress stage should describe the point the work must reach before release is requested. The tradesperson is responsible for proposing accurate, realistic stages and for understanding what they are asking the homeowner to agree.' },
      { title: '2. Both sides agree the schedule', body: 'Before accepting the quote, the homeowner can propose a different split or timing for the stages without changing the tradesperson’s total quoted price. If the homeowner edits the schedule, the tradesperson must accept those changes before the quote can be accepted. Once the payment schedule is agreed and the quote is accepted, both sides are responsible for checking and following the recorded arrangement unless they later agree a variation.' },
      { title: '3. Deposit and materials money can be used to start the job', body: 'An agreed deposit or materials payment is processed through Stripe and released to the tradesperson when paid so agreed materials or mobilisation costs can be covered. The payment screen makes clear when money is intended for immediate release. It is not held for a later completion approval, so homeowners should only authorise an upfront amount they understand and have agreed.' },
      { title: '4. Progress stages are funded before they are needed', body: 'The homeowner funds the next agreed progress stage through Stripe before the tradesperson relies on that stage payment. BuildPair records it as funded, but it is not transferred to the tradesperson merely because the charge succeeded. BuildPair does not require the homeowner to pay the whole accepted quote upfront.' },
      { title: '5. The tradesperson requests release', body: 'When the agreed trigger has genuinely been reached, the tradesperson marks the stage complete and requests release. The tradesperson is responsible for the accuracy of that completion statement. The homeowner is notified and can compare the work with the agreed trigger.' },
      { title: '6. The homeowner decides whether to release', body: 'Before release, the homeowner can approve the stage or raise an issue. Approval is the homeowner’s instruction to BuildPair to arrange the transfer of that funded stage to the tradesperson. The homeowner should therefore inspect the work or otherwise satisfy themselves that the recorded trigger has been reached before approving. Raising an issue before release pauses that BuildPair release workflow while the matter is addressed.' },
      { title: '7. Release decisions are recorded', body: 'BuildPair records the stage, amount, release request and homeowner approval so there is a clear project audit trail. Once Stripe has transferred an approved stage to the tradesperson, BuildPair cannot guarantee that the transfer can simply be undone. A homeowner’s approval does not remove statutory consumer rights, contractual claims, warranties, card-scheme or chargeback rights, or any other rights that cannot lawfully be excluded.' },
      { title: '8. Final payout deductions are transparent', body: 'BuildPair’s service fee is currently 1% of the accepted quote total after agreed deposit stages are excluded. BuildPair also recovers the actual Stripe processing fees recorded for that job. Those amounts are retained from the final tradesperson payout rather than reducing every earlier progress-stage transfer. The final release record shows the gross stage amount, Stripe processing costs, BuildPair service fee and net tradesperson transfer.' },
      { title: '9. Private payments are allowed', body: 'Users can choose a private payment arrangement instead. BuildPair can keep the quote, messages, variations and project history, but it cannot process, control, release, refund or recover privately exchanged money and its staged-payment controls do not apply.' },
      { title: '10. What BuildPair protection does not mean', body: 'BuildPair does not describe its payment workflow as legal escrow and does not guarantee workmanship, completion, defect-free work or recovery of every loss. BuildPair does not inspect each stage or make the approval decision for the homeowner. Tradespeople remain independent businesses and users retain any rights and responsibilities available under applicable law.' },
      { title: '11. Stripe handles payment credentials', body: 'Supported card payments and tradesperson payout onboarding use Stripe. BuildPair stores transaction references and project-payment status needed to run the workflow, but does not store raw card or bank-account numbers entered into Stripe interfaces.' },
    ]}
  />;
}
