import { Linking, View } from 'react-native';
import { Button, Text } from 'react-native-paper';
import { PublicInfoPage, infoStyles } from '@/components/PublicInfoPage';

export default function PrivacyPage() {
  return <PublicInfoPage
    eyebrow="Legal"
    title="Privacy Policy"
    intro="This policy explains the main personal information BuildPair uses to operate accounts, marketplace features, project payments, communications, AI-assisted features and product analytics."
    updated="26 September 2026"
    sections={[
      { title: 'Who this policy applies to', body: 'This policy applies to visitors, homeowners, tradespeople and other users of the BuildPair website and apps.' },
      { title: 'Information we collect', body: 'Depending on how you use BuildPair, information may include account identifiers, contact details, contact preferences, profile and business information, job posts, photos, messages, site-visit arrangements, quotes, payment stages, invoices, reviews, approximate service locations, technical logs, website and app usage, AI requests and generated responses, autosaved form-draft information used for draft recovery and product improvement, and payment-related references supplied by payment providers.' },
      { title: 'Email and text communications', body: 'Where BuildPair offers a choice of email, text message or both, we use the contact details and method selected to provide the requested launch-list, early-access, account or service communication. Choosing service text updates is not treated as consent to unrelated marketing texts. Marketing communication preferences are handled separately. A person who chooses a one-way branded SMS sender is given an alternative way to stop messages because replies to an alphanumeric sender may not be supported.' },
      { title: 'Why we use information', body: 'We use information to create and secure accounts, provide marketplace matching, operate profiles and jobs, enable communication, administer project stages and payments, provide requested launch and account notifications, provide and improve AI-assisted features, prevent abuse and fraud, provide support, understand where visitors and users encounter friction or leave important BuildPair journeys unfinished, improve the service and comply with legal obligations.' },
      { title: 'Visitor analytics', body: 'When someone visits the BuildPair website without signing in, BuildPair may collect first-party statistical information to understand and improve the service. Basic analytics is aggregate by default and can include visit starts, pages viewed, meaningful button or link clicks, scroll-depth milestones, time spent on pages, which named form fields were reached, referral source, campaign parameters, broad device type, browser and operating-system category, language, timezone, screen or viewport size bands, connection category and coarse country, region or town/city location. Basic analytics does not create a persistent visitor identifier or retain an individual browsing journey.' },
      { title: 'Coarse location estimation', body: 'BuildPair first uses coarse location information supplied by the hosting or network layer where available. If that does not provide a useful town or region, the BuildPair server may temporarily use the request IP address with an IP geolocation provider, currently ipwho.is, to estimate country, region and town/city. The raw IP address is not stored in BuildPair visitor analytics. IP geolocation can be inaccurate, especially on mobile networks, VPNs and corporate networks, and BuildPair does not treat it as a street address, exact postcode or precise device location.' },
      { title: 'Optional detailed journey analytics', body: 'A random first-party anonymous browser identifier, normally retained for up to 90 days, and a shorter-lived visit identifier are created only when a visitor explicitly chooses detailed analytics. These identifiers allow BuildPair to understand the sequence of pages and actions in that opted-in visit and estimate new versus returning detailed visitors. They do not contain a name, email address, phone number or raw IP address, and BuildPair does not use device fingerprinting to recreate them. Returning to basic analytics or turning analytics off removes the local identifiers and requests deletion of associated detailed journey records.' },
      { title: 'What visitor analytics deliberately excludes', body: 'BuildPair visitor analytics does not store passwords, authentication secrets, payment-card or bank-account details, the contents typed into form fields, raw IP addresses, precise GPS coordinates, street addresses, exact household location, mouse-movement recordings, hidden keystroke recordings, advertising profiles or cross-site tracking identifiers. Exact device location is not silently requested for analytics.' },
      { title: 'Browser privacy signals and analytics choices', body: 'BuildPair respects supported browser privacy signals used by the analytics code, including Global Privacy Control and Do Not Track where available. Visitors can also use the Cookie & Analytics Storage Policy page to keep basic aggregate analytics, explicitly allow detailed journey analytics or turn visitor analytics off. BuildPair may store a small first-party value to remember that choice. A random visitor identifier is used only for the detailed option.' },
      { title: 'Signed-in product analytics and unfinished journeys', body: 'For signed-in users, BuildPair may record the pages and product steps used, the time of recent activity, device platform and whether important journeys such as posting a job or building a trade profile appear to have been started, completed or left unfinished. This helps BuildPair identify confusing pages, failed journeys and features that need improvement. BuildPair does not use this feature to record passwords, payment-card details, bank details or secret keystroke-by-keystroke recordings.' },
      { title: 'Autosaved drafts', body: 'Some multi-step forms may save a limited draft so a user can recover unfinished work. Where server-side draft recovery is used, BuildPair limits the fields stored for product analysis and support. Sensitive authentication and payment credentials are excluded. Draft information is available only to the user through the relevant feature and to authorised administrators where reasonably needed to support the service, investigate a failed journey or improve BuildPair.' },
      { title: 'Payments, payouts and Stripe', body: 'BuildPair uses Stripe for supported payments, tradesperson onboarding and payouts. Information entered directly into Stripe payment or onboarding interfaces, including payment, bank-account and verification information, is collected by Stripe under the terms and privacy information Stripe presents to the user. BuildPair does not store raw payment-card or bank-account numbers entered into those Stripe interfaces.' },
      { title: 'Payment information BuildPair receives', body: 'BuildPair receives and stores the references and status information needed to operate and reconcile the payment workflow. This can include Stripe customer and connected-account identifiers, PaymentIntent and charge references, transfer, refund and dispute identifiers, payment amounts, stage status, fees and payout-readiness status.' },
      { title: 'Payment-stage and dispute records', body: 'For jobs using BuildPair payments, BuildPair may record when a payment stage is proposed, agreed, funded, marked complete, approved for release, transferred, disputed, refunded or otherwise changed. These records may be used for transaction reconciliation, support, fraud prevention, disputes, accounting and legal compliance.' },
      { title: 'AI-assisted features and request review', body: 'When a BuildPair AI-assisted feature is used, BuildPair may store the request or relevant job/conversation context supplied to that feature together with the generated response, technical status, model and timing information. Authorised administrators may review recent AI requests and responses to detect abuse, investigate failures, understand how people use the feature and improve BuildPair. BuildPair applies automated redaction for common secret and API-key patterns before these AI audit records are stored, but users should still avoid entering passwords, payment credentials, API keys or other unnecessary secrets into AI fields. AI audit records are normally retained for up to 90 days.' },
      { title: 'AI-assisted chat and safety analysis', body: 'Messages in BuildPair job conversations may be analysed by automated systems to provide optional reply suggestions, identify possible scams, threats, targeted abuse or other behaviour that may breach marketplace rules, and help prioritise moderation review. Automated analysis can make mistakes. BuildPair may place a warning or temporary messaging restriction on a conversation where risk indicators are detected, and serious or disputed cases may be reviewed by an authorised human moderator. Users remain responsible for checking any AI-generated draft before sending it.' },
      { title: 'Google business listings and reviews', body: <View style={infoStyles.list}>
        <Text style={infoStyles.item}>If a tradesperson chooses to connect Google reviews, BuildPair uses Google Places API services to search for and retrieve public business-listing information and available Google review content. BuildPair compares the selected listing with saved BuildPair business details such as business name, postcode, phone number and website in order to decide whether the connection can be approved automatically or needs admin review.</Text>
        <Text style={infoStyles.item}>BuildPair stores the Google Place ID and BuildPair’s own connection and verification metadata. Google-supplied place and review content is requested from Google for display rather than treated as BuildPair-owned review data. Google content remains clearly identified as Google Maps content and is kept separate from reviews earned through completed BuildPair jobs.</Text>
        <Text style={infoStyles.item}>Use of Google Maps Platform content is also subject to Google’s terms and privacy information.</Text>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>
          <Button mode="outlined" compact onPress={() => Linking.openURL('https://cloud.google.com/maps-platform/terms')}>Google Maps Platform Terms</Button>
          <Button mode="outlined" compact onPress={() => Linking.openURL('https://policies.google.com/privacy')}>Google Privacy Policy</Button>
        </View>
      </View> },
      { title: 'Public information', body: 'Tradesperson profile information and public marketplace content may be visible to other users or visitors where that is part of the feature. Full public tradesperson profiles require an active paid tradesperson membership. Contact details are not made public merely because a profile is visible. Do not publish sensitive personal information in public profile fields, job descriptions or photos.' },
      { title: 'Service providers', body: 'BuildPair uses specialist providers for functions such as authentication, hosting, databases, payments, email and SMS delivery, media storage, Google business-listing and review content, and AI-assisted features. These providers process information for the services they supply and may also have their own legal obligations and privacy terms. Stripe’s own privacy information applies to data it collects directly through its payment and onboarding services, and Google’s privacy information applies to Google services and content.' },
      { title: 'Retention', body: 'Information is kept only for as long as reasonably needed for the purpose for which it is used, including account operation, launch and service communications, draft recovery, product improvement, dispute handling, fraud prevention, legal compliance, transaction reconciliation and financial record keeping. AI request audit records are normally retained for up to 90 days. Optional detailed-analytics visitor identifiers are intentionally time-limited, normally to 90 days, while aggregate statistics may be retained longer because they are designed not to contain an individual browsing journey. Google Place IDs and BuildPair verification metadata may be retained while a Google business connection exists or as reasonably needed to administer it. Project-payment and dispute records may therefore be retained after a job or account is otherwise inactive where this is reasonably necessary.' },
      { title: 'Your UK data rights', body: 'Subject to applicable law, you may have rights to access, correct, erase or restrict use of personal information, object to certain processing, or request portability. Some rights are subject to legal exceptions and retention requirements, including records that must be kept for financial, fraud-prevention or legal purposes.' },
      { title: 'Security', body: 'BuildPair uses technical and organisational safeguards appropriate to the service and limits raw payment credential handling by using specialist payment-provider interfaces. No internet service can guarantee absolute security, so users should also protect their login credentials and devices.' },
      { title: 'Contact', body: 'Privacy enquiries, communication-preference changes and requests can be sent to info@buildpair.co.uk. If you remain unhappy with how personal information is handled, you may also have the right to complain to the UK Information Commissioner’s Office.' },
    ]}
  />;
}
