import { PublicInfoPage } from '@/components/PublicInfoPage';

export default function PrivacyPage() {
  return <PublicInfoPage
    eyebrow="Legal"
    title="Privacy Policy"
    intro="This policy explains the main personal information BuildPair uses to operate accounts, marketplace features, project payments and communications."
    updated="9 September 2026"
    sections={[
      { title: 'Who this policy applies to', body: 'This policy applies to visitors, homeowners, tradespeople and other users of the BuildPair website and apps.' },
      { title: 'Information we collect', body: 'Depending on how you use BuildPair, information may include account identifiers, contact details, profile and business information, job posts, photos, messages, site-visit arrangements, quotes, payment stages, invoices, reviews, approximate service locations, technical logs and payment-related references supplied by payment providers.' },
      { title: 'Why we use information', body: 'We use information to create and secure accounts, provide marketplace matching, operate profiles and jobs, enable communication, administer project stages and payments, prevent abuse and fraud, provide support, improve the service and comply with legal obligations.' },
      { title: 'Payments, payouts and Stripe', body: 'BuildPair uses Stripe for supported card payments, tradesperson onboarding and payouts. Information entered directly into Stripe payment or onboarding interfaces, including card, bank-account and verification information, is collected by Stripe under the terms and privacy information Stripe presents to the user. BuildPair does not store raw card or bank-account numbers entered into those Stripe interfaces.' },
      { title: 'Payment information BuildPair receives', body: 'BuildPair receives and stores the references and status information needed to operate and reconcile the payment workflow. This can include Stripe customer and connected-account identifiers, PaymentIntent and charge references, transfer, refund and dispute identifiers, payment amounts, stage status, fees and payout-readiness status.' },
      { title: 'Payment-stage and dispute records', body: 'For jobs using BuildPair payments, BuildPair may record when a payment stage is proposed, agreed, funded, marked complete, approved for release, transferred, disputed, refunded or otherwise changed. These records may be used for transaction reconciliation, support, fraud prevention, disputes, accounting and legal compliance.' },
      { title: 'AI-assisted chat and safety analysis', body: 'Messages in BuildPair job conversations may be analysed by automated systems to provide optional reply suggestions, identify possible scams, threats, targeted abuse or other behaviour that may breach marketplace rules, and help prioritise moderation review. Automated analysis can make mistakes. BuildPair may place a warning or temporary messaging restriction on a conversation where risk indicators are detected, and serious or disputed cases may be reviewed by an authorised human moderator. Users remain responsible for checking any AI-generated draft before sending it.' },
      { title: 'Public information', body: 'Tradesperson profile information and public marketplace content may be visible to other users or visitors where that is part of the feature. Do not publish sensitive personal information in public profile fields, job descriptions or photos.' },
      { title: 'Service providers', body: 'BuildPair uses specialist providers for functions such as authentication, hosting, databases, payments, email delivery, media storage and AI-assisted features. These providers process information for the services they supply and may also have their own legal obligations and privacy terms. Stripe’s own privacy information applies to data it collects directly through its payment and onboarding services.' },
      { title: 'Retention', body: 'Information is kept only for as long as reasonably needed for the purpose for which it is used, including account operation, dispute handling, fraud prevention, legal compliance, transaction reconciliation and financial record keeping. Project-payment and dispute records may therefore be retained after a job or account is otherwise inactive where this is reasonably necessary.' },
      { title: 'Your UK data rights', body: 'Subject to applicable law, you may have rights to access, correct, erase or restrict use of personal information, object to certain processing, or request portability. Some rights are subject to legal exceptions and retention requirements, including records that must be kept for financial, fraud-prevention or legal purposes.' },
      { title: 'Security', body: 'BuildPair uses technical and organisational safeguards appropriate to the service and limits raw payment credential handling by using specialist payment-provider interfaces. No internet service can guarantee absolute security, so users should also protect their login credentials and devices.' },
      { title: 'Contact', body: 'Privacy enquiries and requests can be sent to info@buildpair.co.uk. If you remain unhappy with how personal information is handled, you may also have the right to complain to the UK Information Commissioner’s Office.' },
    ]}
  />;
}
