import { Linking, View } from 'react-native';
import { Text } from 'react-native-paper';
import { Button } from '@/components/BrandButton';
import { PublicInfoPage, infoStyles } from '@/components/PublicInfoPage';
import { BUILDPAY_OPEN } from '@/lib/launch-config';

export default function TermsPage() {
  return <PublicInfoPage
    eyebrow="Legal"
    title="BuildPair Terms of Use"
    intro={BUILDPAY_OPEN ? 'These terms apply to all BuildPair users. BuildPay-specific notices shown during payment also form part of that transaction.' : 'These terms apply to all BuildPair users. BuildPay job-payment processing and payouts are not available during the current launch phase. Homeowners and tradespeople arrange and agree payment directly; BuildPair does not receive, hold, refund or protect those funds. BuildPay-specific sections below apply only if BuildPay is made available in future.'}
    updated="4 October 2026"
    sections={[
      { title: '1. The platform', body: 'BuildPair provides marketplace, introduction and project-workflow technology that helps homeowners and tradespeople find each other, communicate, arrange visits, quote, agree project stages, record variations and manage project records. BuildPair is not the contractor, employer or person carrying out the building work.' },
      { title: '2. Accounts and information', body: 'You must provide accurate information, keep your account secure and only make claims about identity, business status, qualifications, experience, insurance or work that you can support. One BuildPair login may enable separate homeowner and tradesperson modes.' },
      { title: '3. Marketplace conduct', body: 'Users must not post unlawful, misleading, abusive, discriminatory, fraudulent or unsafe content; manipulate reviews; impersonate another person or business; misuse contact details; threaten or harass another user; or use BuildPair to facilitate unlawful work.' },
      { title: '4. Local matching and public location', body: 'BuildPair is designed to keep marketplace matching local. Tradespeople choose a genuine base postcode and working radius, and open marketplace jobs are matched using service-area information. Before a site visit or job award, BuildPair may show only an area, outward postcode or approximate location rather than a homeowner’s full street address. Full trader postcodes are not displayed publicly.' },
      { title: '5. Private job addresses and site visits', body: 'A homeowner may store a private street address and access notes for a job. That private address is not part of the public marketplace listing. BuildPair may disclose it to a particular tradesperson after the homeowner confirms that tradesperson’s site visit, or after the homeowner awards that tradesperson the job. A tradesperson receiving a private address must use it only for the relevant visit or project and must not republish it or use it for unrelated marketing.' },
      { title: '6. Pre-quote site visits', body: 'A tradesperson may request a site visit where photos and descriptions are not enough to quote responsibly. A confirmed site visit is an inspection opportunity only; it does not award the job or agree a price. After the visit, users should return to the BuildPair project and use the structured quote process so the scope, price, exclusions, timing and payment route are recorded clearly.' },
      { title: '7. Tradesperson responsibilities', body: 'Tradespeople remain responsible for their competence, legal and professional requirements, insurance, quotes, scope, exclusions, payment schedules, completion statements and variations. A tradesperson using BuildPay must only request release of a controlled payment stage when the recorded completion point has genuinely been reached.' },
      { title: '8. Homeowner responsibilities', body: 'Homeowners remain responsible for choosing whom to appoint and for agreeing the scope, price, timing and payment schedule. Before making a materials payment, funding a stage or approving release, the homeowner should check the amount, purpose and relevant completion point.' },
      { title: '9. Quotes and payment schedules', body: 'A BuildPair quote may include labour/service, materials, VAT, scope, exclusions, start date, duration and a payment schedule. Before accepting the quote, the homeowner may propose changes to the split or timing of service stages without changing the total quote price or quoted materials amount. Any revised schedule must be accepted by the tradesperson.' },
      { title: '10. Choosing BuildPay or direct payment', body: 'After an eligible quote is accepted, the homeowner may choose BuildPay or a direct payment arrangement. BuildPay uses Stripe and the BuildPair stage-release workflow. Direct payment means the homeowner and tradesperson arrange the money between themselves. Once a BuildPay payment has been made for a job, users cannot simply relabel that same payment as direct in order to bypass the recorded BuildPay workflow.' },
      { title: '11. Stripe and payout onboarding', body: 'BuildPair uses Stripe for supported BuildPay payments, connected tradesperson onboarding and payouts. Tradespeople must complete the required Stripe onboarding before BuildPay can be used with them. Stripe handles payment, identity and payout information entered into Stripe interfaces under the terms and privacy information it presents. BuildPair receives the account, transaction and status references needed to operate the BuildPay workflow.' },
      { title: '12. BuildPay materials', body: 'Where the accepted quote contains materials, the BuildPay schedule must contain the exact quoted materials amount. That materials payment is paid first and is transferred for procurement when Stripe confirms the payment. It is not subject to a later workmanship-release approval.' },
      { title: '13. Controlled BuildPay stages', body: 'Deposits, progress stages and final stages paid through BuildPay are controlled payments. Stripe processes the homeowner payment first, but BuildPair does not instruct transfer to the tradesperson merely because the card charge succeeded. The tradesperson must reach the agreed trigger and request release. The homeowner then approves release or raises an issue. BuildPair may keep later stages unavailable until earlier stages are completed.' },
      { title: '14. BuildPay issues and escalation', body: 'If the homeowner raises an issue before an unreleased controlled stage is transferred, BuildPair pauses that release. The tradesperson can add a response. The homeowner may resolve the issue and return the stage to release review, request a refund of the unreleased stage, or escalate the record for BuildPair admin attention. BuildPair may facilitate communication, preserve evidence and administer the platform workflow, but does not inspect the property or automatically determine contractual liability, workmanship quality or legal entitlement.' },
      { title: '15. Refunds, chargebacks and reversals', body: 'Where an unreleased BuildPay payment is eligible for refund, including where the parties agree a refund, BuildPair may submit the relevant refund instruction through Stripe. Once a transfer has already been made to a tradesperson, BuildPair cannot guarantee reversal. Stripe, banks, card networks, fraud processes, refunds and chargebacks may operate separately from the BuildPair project status.' },
      { title: '16. Fees and payouts', body: 'The party who requests BuildPay carries its cost. When the tradesperson requests it, the applicable BuildPair fee and recorded payment-processing costs are absorbed from controlled service payouts. When the homeowner requests it, a separate BuildPay service fee is added to the homeowner’s total and disclosed before agreement and payment. Materials and VAT are excluded from the labour/service amount used to calculate the BuildPair platform fee. The applicable fee, total payable and payout treatment must be shown before commitment; the transaction’s agreed terms govern that job. Later rate changes do not retrospectively alter an agreed fee.' },
      { title: '17. Direct payments outside BuildPair', body: 'Users may choose to pay the tradesperson directly, including by bank transfer or another method they agree. BuildPair may keep the quote, messages, variations and project record and may allow each side to record that a direct payment was sent or received. Those confirmations are user declarations only. BuildPair does not receive, hold, process, protect, release, refund, recover or independently verify money paid directly between users.' },
      { title: '18. Responsibility for direct-payment jobs', body: 'For money paid directly, BuildPair’s role in relation to that payment is limited to the marketplace introduction and any project record the users choose to keep on the platform. The homeowner and tradesperson remain responsible for their own contract, work, invoices, taxes, payment conduct and disputes. Nothing in these terms removes statutory consumer rights, contractual rights, payment rights or any duty or liability that cannot lawfully be excluded or limited.' },
      { title: '19. Payment and workmanship limits', body: 'BuildPay is a staged-payment workflow, not a legal escrow account, insurance policy, workmanship guarantee or promise of a refund. BuildPair does not inspect the work, certify completion, guarantee a tradesperson or decide whether a stage complies with a contract, regulation or professional standard. The platform record is intended to improve clarity and evidence, not to replace professional inspection, legal advice or rights provided by law.' },
      { title: '20. AI, BuildPair reviews and availability', body: 'BuildPair may use automated systems for job drafting, trade matching, quote wording, message suggestions and safety signals. AI output may be inaccurate and users remain responsible for what they send and for real-world decisions. Reviews submitted through BuildPair must reflect genuine experiences. Features may change and uninterrupted availability is not guaranteed.' },
      { title: '21. Google business listings and reviews', body: <View style={infoStyles.list}>
        <Text style={infoStyles.item}>An eligible tradesperson may choose to connect a Google business listing. The tradesperson must select a listing that genuinely represents their business and must not attempt to connect another business’s listing or misrepresent Google-supplied ratings or reviews.</Text>
        <Text style={infoStyles.item}>BuildPair may compare the selected listing with business details held on BuildPair and may either approve the connection automatically, place it into admin review or reject it. Google reviews remain separate from BuildPair job reviews. A connected Google listing does not mean that Google endorses BuildPair, that BuildPair endorses the tradesperson, or that BuildPair has independently verified the truth of each Google review.</Text>
        <Text style={infoStyles.item}>Google-supplied listing and review content is displayed subject to Google Maps Platform requirements. By using BuildPair features that display Google Maps Platform content, users also agree to the applicable Google Maps and Google terms presented below.</Text>
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>
          <Button mode="outlined" compact onPress={() => Linking.openURL('https://cloud.google.com/maps-platform/terms')}>Google Maps Platform Terms</Button>
          <Button mode="outlined" compact onPress={() => Linking.openURL('https://policies.google.com/terms')}>Google Terms of Service</Button>
        </View>
      </View> },
      { title: '22. Public tradesperson profiles', body: 'Full public tradesperson profiles are available only while the relevant paid tradesperson membership is active. A free or inactive profile may be privately previewed by its owner, but an external shared link does not unlock the full public profile. Signing up or signing in as a homeowner does not override that restriction. BuildPair does not publish a tradesperson’s direct email address or phone number merely because their profile is publicly visible; contact details may become available through an appropriate project relationship such as an accepted job.' },
      { title: 'Memberships and search placement', body: 'A paid membership provides the features and allowances shown for that plan. It does not guarantee enquiries, quotes, work, earnings or a particular search position. Promotional and featured placement is not a recommendation or independent certification of workmanship. Pre-launch access and founding offers are subject to the published eligibility and launch terms. Marketplace and billing gates remain in effect until the relevant services open.' },
      { title: '23. Age and account eligibility', body: 'BuildPair account and marketplace tools are intended for people aged 18 or over. Users must not create an account or use marketplace features on behalf of a child. This age rule is a contractual eligibility requirement and is not described as highly effective age assurance.' },
      { title: '24. Illegal and harmful content', body: 'BuildPair does not permit content or conduct that is illegal or that creates an unacceptable safety risk. This includes terrorism content; child sexual exploitation or abuse, including grooming; unlawful hate, threats, stalking or harassment; intimate-image abuse or cyberflashing; fraud and scams; unlawful drugs or weapons content; sexual exploitation; and content that unlawfully encourages or assists suicide or serious self-harm. BuildPair may use automated and human moderation, restrict visibility or messaging, remove content, preserve relevant records and warn, restrict or suspend accounts where proportionate.' },
      { title: '25. Safety reports and moderation complaints', body: 'Anyone can report suspected illegal or harmful content through the public Report page without creating a BuildPair account. Signed-in users can also submit an account-linked marketplace report. A person who believes BuildPair has handled a safety report or moderation decision incorrectly may ask for review by emailing info@buildpair.co.uk and including the relevant report reference, account email or content reference where available. Do not download, copy or send suspected child sexual abuse images or videos to BuildPair; provide only enough information to identify where the material appears. Where a legal reporting duty applies, BuildPair may report relevant child sexual exploitation and abuse material or activity to the appropriate authority.' },
      { title: '26. Contact', body: 'Questions about these terms, service-area changes, private address handling, safety reporting or BuildPay can be sent to info@buildpair.co.uk.' },
    ]}
  />;
}
