import { PublicInfoPage } from '@/components/PublicInfoPage';

export default function TermsPage() {
  return <PublicInfoPage
    eyebrow="Legal"
    title="BuildPair Terms of Use"
    intro="These terms explain the rules for using BuildPair as a homeowner, tradesperson or visitor. Payment-specific information shown when a job is accepted forms part of the relevant transaction terms."
    updated="8 September 2026"
    sections={[
      { title: '1. The platform', body: 'BuildPair provides marketplace and project-workflow technology that helps homeowners and tradespeople discover each other, communicate, arrange site visits, quote, agree project stages, record variations and manage project payments. BuildPair is not itself the contractor, employer, building professional or person carrying out the work.' },
      { title: '2. Accounts and information', body: 'You must provide accurate information, keep your account secure and only make claims about qualifications, experience, insurance, work, identity or business status that you can support. One login may enable separate homeowner and tradesperson modes.' },
      { title: '3. Marketplace conduct', body: 'Users must not post unlawful, misleading, abusive, discriminatory, fraudulent or unsafe content; manipulate reviews; impersonate another person or business; misuse contact details; threaten or harass another user; pressure users to bypass BuildPair safeguards; or use BuildPair to facilitate unlawful work.' },
      { title: '4. Tradesperson responsibilities', body: 'Tradespeople remain responsible for deciding whether work is within their competence and for holding any licence, registration, qualification, insurance or permission required by law or appropriate industry practice. A tradesperson is responsible for the accuracy and suitability of their quote, scope, exclusions, materials allowance, proposed payment stages, completion statements and variations.' },
      { title: '5. Homeowner responsibilities', body: 'Homeowners remain responsible for deciding who to appoint, checking material credentials and agreeing scope, price, timing and payment arrangements. BuildPair information can assist that decision but does not replace appropriate checks. Before approving release of a controlled payment stage, the homeowner should inspect or otherwise satisfy themselves that the agreed trigger has been reached.' },
      { title: '6. Site visits, quotes and payment-stage agreement', body: 'A tradesperson may arrange a site visit through the BuildPair job before issuing a formal quote. A BuildPair quote may include labour, materials, VAT, a proposed start date, scope, exclusions and a proposed payment schedule. Before accepting a quote, a homeowner may propose changes to the timing or split of payment stages without changing the tradesperson’s total quote price. If payment stages are edited, the tradesperson must agree the revised schedule before the quote can be accepted.' },
      { title: '7. Choosing the payment route', body: 'After an eligible quote is accepted, the homeowner may choose BuildPair staged payments or a private payment arrangement. Selecting BuildPair staged payments records acceptance of the payment terms shown for that job and the current version of these terms. A job that has already collected a BuildPair payment cannot simply be switched to a private payment route to bypass the recorded payment workflow.' },
      { title: '8. BuildPair staged payments', body: 'BuildPair staged payments are processed through Stripe. BuildPair may arrange for an agreed payment stage to be charged to the homeowner before that stage is transferred to the tradesperson. For controlled stages, the payment can be recorded as funded, the tradesperson can later record that the agreed trigger has been reached, and the homeowner can approve release or raise an issue before BuildPair instructs the relevant transfer. BuildPair does not describe this arrangement as a legal escrow account and does not promise that funds have any legal status beyond the arrangements provided by Stripe and the applicable payment rules.' },
      { title: '9. Materials payments and deposits', body: 'A materials payment is intended for agreed project materials and may be transferred to the tradesperson when the homeowner makes that payment so the materials can be bought. Once a materials payment has been transferred to the tradesperson, it is no longer awaiting BuildPair release approval. A deposit may instead be funded first and released when the agreed deposit or start trigger is reached. Users should only agree advance amounts they understand and consider appropriate for the job.' },
      { title: '10. Progress and final stages', body: 'For a BuildPair-controlled deposit, progress stage or final stage, the homeowner may be asked to fund the stage before the tradesperson progresses it. A funded stage is not treated as released merely because the card charge succeeded. The tradesperson records when the agreed trigger is reached and requests release. The homeowner can then approve release or raise an issue. BuildPair may prevent later stages from being funded until earlier stages are released so the project follows the agreed order.' },
      { title: '11. Issues, disputes, refunds and chargebacks', body: 'If a homeowner raises an issue before an unreleased controlled stage is transferred, BuildPair may pause release while the parties communicate or the matter is reviewed. Stripe or card-network disputes, refunds, fraud checks and chargebacks may operate separately from the BuildPair project status and are subject to provider and card-network rules. BuildPair cannot promise that every dispute will be resolved in either user’s favour. Where money has already been transferred, refunds or reversals may require recovery from the relevant connected account or other payment action.' },
      { title: '12. Fees and payouts', body: 'BuildPair may charge a transaction fee on jobs using BuildPair staged payments. The applicable rate is shown in pricing or payment information and may change for future jobs. The current implementation is designed so the configured BuildPair transaction fee is retained from the final tradesperson payout rather than deducted from every earlier project stage. Stripe processing, connected-account and payout rules may also apply. Tradespeople must complete Stripe onboarding before BuildPair payments can be used with them. BuildPair does not store raw card or bank-account numbers supplied to Stripe.' },
      { title: '13. Private or off-platform payments', body: 'Users may choose to arrange payments privately rather than using BuildPair payment processing. If they do, BuildPair can retain the project record, messages, agreed quote and variations, but BuildPair cannot process, control, release, refund or recover money paid outside BuildPair. BuildPair payment-stage controls, Stripe payment evidence and provider-based payment workflow do not apply to those private transactions. This limitation applies to both homeowners and tradespeople.' },
      { title: '14. Workmanship and project protection limits', body: 'BuildPair payment-stage controls are designed to improve clarity and reduce avoidable payment disputes, but they are not a guarantee of workmanship, completion, defect-free work, legal compliance or recovery of every loss. BuildPair does not inspect every project and does not replace building control, planning authorities, insurers, qualified professionals, courts, ombudsman schemes or other rights available under law.' },
      { title: '15. AI-assisted features and moderation', body: 'BuildPair may use automated systems for trade triage, job-spec drafting, quote wording, message suggestions and marketplace safety signals. AI-generated output is a draft and may be inaccurate. Users must check what they send and remain responsible for decisions requiring real-world professional judgement. BuildPair may warn, restrict, suspend or review accounts or content where reasonably necessary for safety, fraud prevention, legal compliance or enforcement of these terms.' },
      { title: '16. Reviews, availability and liability', body: 'Reviews must reflect genuine experiences. BuildPair may distinguish between activity supported by BuildPair project or payment records and activity that took place privately. Features may change as BuildPair develops and uninterrupted availability is not guaranteed. Nothing in these terms excludes liability that cannot legally be excluded. To the extent permitted by law, BuildPair is not responsible for the quality, safety, legality or completion of work carried out by independent tradespeople, or for indirect losses arising from those arrangements.' },
      { title: '17. Contact', body: 'Questions about these terms or BuildPair payment-stage controls can be sent to info@buildpair.co.uk.' },
    ]}
  />;
}
