import { PublicInfoPage } from '@/components/PublicInfoPage';

export default function TermsPage() {
  return <PublicInfoPage
    eyebrow="Legal"
    title="BuildPair Terms of Use"
    intro="These terms apply to homeowners, tradespeople and visitors using BuildPair. BuildPay is BuildPair's staged-payment workflow. Where BuildPay is used, the payment notices shown before funding or release also form part of the relevant transaction terms."
    updated="11 September 2026"
    sections={[
      { title: '1. The platform', body: 'BuildPair provides marketplace and project-workflow technology that helps homeowners and tradespeople find each other, communicate, quote, agree project stages, record variations and manage project payments. BuildPair is not the contractor, employer or person carrying out the work.' },
      { title: '2. Accounts and information', body: 'You must provide accurate information, keep your account secure and only make claims about identity, business status, qualifications, experience, insurance or work that you can support. One BuildPair login may enable separate homeowner and tradesperson modes.' },
      { title: '3. Marketplace conduct', body: 'Users must not post unlawful, misleading, abusive, discriminatory, fraudulent or unsafe content; manipulate reviews; impersonate another person or business; misuse contact details; threaten or harass another user; or use BuildPair to facilitate unlawful work.' },
      { title: '4. Local matching and service areas', body: 'BuildPair is designed to keep marketplace matching local. Tradespeople choose a genuine base postcode and working radius, and open marketplace jobs are matched using that service area. A tradesperson’s published base location is locked after the profile is first published so it cannot be repeatedly moved simply to access distant jobs. The working radius may be adjusted within BuildPair limits. If a tradesperson genuinely moves home or relocates the business base, they can contact BuildPair support to request a location update and BuildPair may ask for reasonable evidence of the new location. Full trader postcodes are not displayed publicly.' },
      { title: '5. Tradesperson responsibilities', body: 'Tradespeople remain responsible for their competence, legal and professional requirements, insurance, quotes, scope, exclusions, payment schedules, completion statements and variations. A tradesperson must only request release of a work stage when the recorded completion point has genuinely been reached.' },
      { title: '6. Homeowner responsibilities', body: 'Homeowners remain responsible for choosing whom to appoint and for agreeing the scope, price, timing and payment schedule. Before making a BuildPay payment or approving release of a funded stage, the homeowner should check the amount, purpose and relevant completion point.' },
      { title: '7. Quotes and payment schedules', body: 'A BuildPair quote may include labour, materials, VAT, scope, exclusions, start date, duration and a payment schedule. Before accepting the quote, the homeowner may propose changes to the split or descriptions of payment stages without changing the total quote price. Any revised schedule must be accepted by the tradesperson.' },
      { title: '8. Choosing a payment route', body: 'After an eligible quote is accepted, the homeowner may choose BuildPay or a private payment arrangement. Choosing BuildPay confirms acceptance of the agreed payment schedule, these terms and any payment notice shown at that point. Once BuildPay has processed a payment for a job, the recorded BuildPay workflow for that payment cannot simply be bypassed by switching it to a private arrangement.' },
      { title: '9. Stripe and payout onboarding', body: 'BuildPay uses Stripe for supported card payments, connected tradesperson onboarding and payouts. Tradespeople must complete the required Stripe onboarding before BuildPay can be used with them. Stripe handles payment, identity and payout information entered into Stripe interfaces under the terms and privacy information it presents to the user. BuildPair receives the account, transaction and status references needed to operate BuildPay.' },
      { title: '10. Materials and initial funding', body: 'Materials are the only BuildPay stage type released automatically when Stripe confirms payment. Where an agreed staged schedule begins with materials followed by a work stage, BuildPay may fund both amounts together. The materials amount is released to the tradesperson’s connected Stripe account, while the work-stage amount remains funded and unreleased until the recorded completion point and approval process are completed.' },
      { title: '11. Deposits, progress and final stages', body: 'Deposits, progress stages and final stages are controlled BuildPay funds rather than automatic materials releases. The homeowner funds the agreed amount first. The tradesperson then requests release after reaching the recorded completion point, and the homeowner may approve release or raise an issue. Approval is the homeowner’s instruction to BuildPair to arrange the relevant Stripe transfer. BuildPair may keep later stages unavailable until earlier stages are completed and released.' },
      { title: '12. BuildPay issues, refunds and chargebacks', body: 'If the homeowner raises an issue before an unreleased funded stage is transferred, BuildPay pauses that release while the issue is addressed. The tradesperson may respond, the homeowner may resolve the issue and return the stage to release review, and either party may escalate the issue for BuildPair review. An internal BuildPay dispute is not an automatic refund and is separate from any Stripe, card-network or chargeback process. Once a transfer has been made, BuildPair cannot guarantee that it can be reversed.' },
      { title: '13. Fees and payouts', body: 'For jobs using BuildPay, the current BuildPair platform fee applies to labour/service only and is allocated across eligible service-stage payouts. Materials do not carry the BuildPair percentage fee. BuildPair also recovers the actual Stripe processing costs recorded for the job progressively from service payouts. Release records may show the contract stage amount, BuildPair fee, Stripe processing costs and net tradesperson transfer. Any change to rates or fee treatment applies only as disclosed for the relevant future transaction.' },
      { title: '14. Payout timing', body: 'A BuildPay release to a tradesperson’s connected Stripe account is not a promise that the same amount has already reached the tradesperson’s bank account. Stripe controls bank payout availability and timing, which can vary by account, bank, verification status and payout method.' },
      { title: '15. Private payments', body: 'Users may arrange payments privately. BuildPair can retain the quote, messages, variations and project record, but BuildPay cannot process, pause, release, refund or recover money paid outside BuildPair. BuildPay stage controls and Stripe payment records do not apply to those private payments.' },
      { title: '16. Payment and workmanship limits', body: 'BuildPay is not an escrow service. BuildPair does not inspect the work or independently decide whether a stage is complete. BuildPay is not a guarantee of workmanship, completion, legal compliance or recovery of loss. Nothing in these terms removes statutory consumer rights, contractual rights, warranties, payment-scheme rights or any liability that cannot lawfully be excluded.' },
      { title: '17. AI, reviews and availability', body: 'BuildPair may use automated systems for job drafting, trade matching, quote wording, message suggestions and safety signals. AI output may be inaccurate and users remain responsible for what they send and for real-world decisions. Reviews must reflect genuine experiences. Features may change and uninterrupted availability is not guaranteed.' },
      { title: '18. Contact', body: 'Questions about these terms, service-area changes or BuildPay can be sent to info@buildpair.co.uk.' },
    ]}
  />;
}
